// projects/create-remult/templates/auth/vue/src/demo/auth/CheckAuth.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { type UserInfo, remult } from "remult";

const user = ref<UserInfo | undefined | "loading">("loading");

onMounted(async () => {
  user.value = await remult.initUser();
});
</script>

<template>
  <div v-if="user === 'loading'">Auth: ⌛</div>
  <div v-else-if="remult.authenticated()">
    Auth:✅ Hello {{ remult.user?.name }}
    <a href="/auth/signout">Sign Out</a>
  </div>
  <div v-else>
    Auth:✅ Not authenticated, <a href="/auth/signin">Sign In</a>
  </div>
</template>

// projects/create-remult/templates/auth/sveltekit/src/demo/auth/CheckAuth.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { remult, type UserInfo } from "remult";

  let user: UserInfo | undefined | "loading" = "loading";

  onMount(async () => {
    user = await remult.initUser();
  });
</script>

{#if user === "loading"}
  <div>Auth: ⌛</div>
{:else if remult.authenticated()}
  <div>
    Auth:✅ Hello {remult.user?.name}
    <a href="/auth/signout">Sign Out</a>
  </div>
{:else}
  <div>
    Auth:✅ Not authenticated, <a href="/auth/signin">Sign In</a>
  </div>
{/if}
