// projects/create-remult/templates/crud/vue/src/demo/todo/Todo.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { remult } from "remult";
import { Task } from "./Task";

const taskRepo = remult.repo(Task);
const tasks = ref<Task[]>([]);
const page = ref(1);
const fetchTasks = async () => {
  tasks.value = await taskRepo.find({
    page: page.value,
    limit: 5,
  });
};
onMounted(fetchTasks);
watch(page, fetchTasks);

const newTaskTitle = ref("");
async function addTask() {
  try {
    const newTask = await taskRepo.insert({ title: newTaskTitle.value });
    tasks.value.push(newTask);
    newTaskTitle.value = "";
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
async function saveTask(task: Task) {
  try {
    await taskRepo.save(task);
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
async function deleteTask(task: Task) {
  try {
    await taskRepo.delete(task);
    tasks.value = tasks.value.filter((t) => task !== t);
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
</script>
<template>
  <div>
    <h1>Todos</h1>
    <main>
      <form @submit.prevent="addTask()">
        <input v-model="newTaskTitle" placeholder="What needs to be done?" />
        <button>Add</button>
      </form>
      <div v-for="task in tasks">
        <input
          type="checkbox"
          v-model="task.completed"
          @change="saveTask(task)"
        />
        {{ task.title }}
        <button @click="deleteTask(task)">Delete</button>
      </div>
    </main>
    <footer>
      <button @click="page--" :disabled="page <= 1">Previous</button>
      <span>Page {{ page }}</span>
      <button @click="page++">Next</button>
    </footer>
  </div>
</template>

// projects/create-remult/templates/crud/sveltekit/src/demo/todo/Todo.svelte
<script lang="ts">
  import { remult } from "remult";
  import { onMount } from "svelte";
  import { Task } from "./Task";

  let tasks: Task[] = [];
  let page = 1;

  onMount(async () => {
    tasks = await remult.repo(Task).find({
      page: page,
      limit: 5,
    });
  });
  let newTaskTitle = "";
  const addTask = async () => {
    const newTask = await remult.repo(Task).insert({ title: newTaskTitle });
    tasks = [...tasks, newTask];
    newTaskTitle = "";
  };
  const setCompleted = async (task: Task, completed: boolean) => {
    await remult.repo(Task).save({ ...task, completed });
  };
  const deleteTask = async (task: Task) => {
    await remult.repo(Task).delete(task);
    tasks = tasks.filter((c) => c.id !== task.id);
  };
</script>

<div>
  <strong>Todos</strong>
  <main>
    <form on:submit|preventDefault={addTask}>
      <input bind:value={newTaskTitle} placeholder="What needs to be done?" />
      <button>Add</button>
    </form>
    {#each tasks as task}
      <div>
        <input
          type="checkbox"
          bind:checked={task.completed}
          on:change={(e) => setCompleted(task, e.target?.checked)}
        />
        <span>{task.title}</span>
        <button on:click={() => deleteTask(task)}>Delete</button>
      </div>
    {/each}
  </main>
  <footer>
    <button on:click={() => (page -= 1)} disabled={page === 1}>
      Previous
    </button>
    <span>Page {page}</span>
    <button on:click={() => (page += 1)}>Next</button>
  </footer>
</div>
