// projects/create-remult/templates/crud/vue/src/demo/todo/Todo.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { remult } from "remult";
import { Task } from "./Task";

const taskRepo = remult.repo(Task);
const tasks = ref<Task[]>([]);
const page = ref(1);
const fetchTasks = async () => {
  tasks.value = await taskRepo.find({
    page: page.value,
    limit: 5,
  });
};
onMounted(fetchTasks);
watch(page, fetchTasks);

const newTaskTitle = ref("");
async function addTask() {
  try {
    const newTask = await taskRepo.insert({ title: newTaskTitle.value });
    tasks.value.push(newTask);
    newTaskTitle.value = "";
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
async function saveTask(task: Task) {
  try {
    await taskRepo.save(task);
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
async function deleteTask(task: Task) {
  try {
    await taskRepo.delete(task);
    tasks.value = tasks.value.filter((t) => task !== t);
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
</script>
<template>
  <div>
    <h1>Todos</h1>
    <main>
      <form @submit.prevent="addTask()">
        <input v-model="newTaskTitle" placeholder="What needs to be done?" />
        <button>Add</button>
      </form>
      <div v-for="task in tasks">
        <input
          type="checkbox"
          v-model="task.completed"
          @change="saveTask(task)"
        />
        {{ task.title }}
        <button @click="deleteTask(task)">Delete</button>
      </div>
    </main>
    <footer>
      <button @click="page--" :disabled="page <= 1">Previous</button>
      <span>Page {{ page }}</span>
      <button @click="page++">Next</button>
    </footer>
  </div>
</template>

// projects/create-remult/templates/crud/angular/src/app/demo/todo/todo.component.ts
import { Component, type OnInit } from "@angular/core";
import { FormsModule } from "@angular/forms";

import { Task } from "../../../demo/todo/Task.js";
import { repo } from "remult";

@Component({
  selector: "app-todo",
  standalone: true,
  imports: [FormsModule],

  templateUrl: "./todo.component.html",
})
export class TodoComponent implements OnInit {
  tasks: Task[] = [];
  page = 1;
  ngOnInit() {
    this.loadTasks();
  }
  async loadTasks() {
    this.tasks = await repo(Task).find({
      page: this.page,
      limit: 5,
    });
  }
  setPage(delta: number) {
    this.page += delta;
    this.loadTasks();
  }
  newTaskTitle = "";
  async addTask() {
    try {
      const newTask = await repo(Task).insert({ title: this.newTaskTitle });
      this.tasks.push(newTask);
      this.newTaskTitle = "";
    } catch (error: any) {
      alert(error.message);
    }
  }
  async saveTask(task: Task) {
    try {
      await repo(Task).save(task);
    } catch (error: any) {
      alert(error.message);
    }
  }
  async deleteTask(task: Task) {
    await repo(Task).delete(task);
    this.tasks = this.tasks.filter((t) => t !== task);
  }
}

<strong> Todos </strong>
<main>
  <form (submit)="addTask()">
    <input
      placeholder="What needs to be done?"
      [(ngModel)]="newTaskTitle"
      name="newTaskTitle"
    />
    <button>Add</button>
  </form>
  @for ( task of tasks; track task.id) {
  <div>
    <input
      type="checkbox"
      [(ngModel)]="task.completed"
      (change)="saveTask(task)"
    />
    {{ task.title }}
    <button (click)="deleteTask(task)">Delete</button>
  </div>
  }
</main>
<footer>
  <button (click)="setPage(-1)" [disabled]="page <= 1">prev</button>
  <span>Page {{ page }}</span>
  <button (click)="setPage(+1)">next</button>
</footer>
