// docs/interactive/src/content/tutorial/1-basics/3-manipulating-data/1-Insert/_solution/frontend/Todo.tsx
import { useEffect, useState, type FormEvent } from 'react'
import { Task } from '../shared/Task.js'
import { repo } from 'remult'

const taskRepo = repo(Task)

export function Todo() {
  const [tasks, setTasks] = useState<Task[]>([])
  const [newTaskTitle, setNewTaskTitle] = useState('')

  async function addTask(e: FormEvent) {
    e.preventDefault()
    try {
      const newTask = await taskRepo.insert({ title: newTaskTitle })
      setTasks([...tasks, newTask])
      setNewTaskTitle('')
    } catch (error: any) {
      alert((error as { message: string }).message)
    }
  }
  useEffect(() => {
    taskRepo.find().then(setTasks)
  }, [])

  return (
    <div>
      <h1>Todos</h1>
      <main>
        <form onSubmit={addTask}>
          <input
            value={newTaskTitle}
            placeholder="What needs to be done?"
            onChange={(e) => setNewTaskTitle(e.target.value)}
          />
          <button>Add</button>
        </form>
        {tasks.map((task) => {
          return (
            <div key={task.id}>
              <input type="checkbox" checked={task.completed} />
              {task.title}
            </div>
          )
        })}
      </main>
    </div>
  )
}

// projects/create-remult/templates/crud/vue/src/demo/todo/Todo.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { remult } from "remult";
import { Task } from "./Task";

const taskRepo = remult.repo(Task);
const tasks = ref<Task[]>([]);
const page = ref(1);
const fetchTasks = async () => {
  tasks.value = await taskRepo.find({
    page: page.value,
    limit: 5,
  });
};
onMounted(fetchTasks);
watch(page, fetchTasks);

const newTaskTitle = ref("");
async function addTask() {
  try {
    const newTask = await taskRepo.insert({ title: newTaskTitle.value });
    tasks.value.push(newTask);
    newTaskTitle.value = "";
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
async function saveTask(task: Task) {
  try {
    await taskRepo.save(task);
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
async function deleteTask(task: Task) {
  try {
    await taskRepo.delete(task);
    tasks.value = tasks.value.filter((t) => task !== t);
  } catch (error: unknown) {
    alert((error as { message: string }).message);
  }
}
</script>
<template>
  <div>
    <h1>Todos</h1>
    <main>
      <form @submit.prevent="addTask()">
        <input v-model="newTaskTitle" placeholder="What needs to be done?" />
        <button>Add</button>
      </form>
      <div v-for="task in tasks">
        <input
          type="checkbox"
          v-model="task.completed"
          @change="saveTask(task)"
        />
        {{ task.title }}
        <button @click="deleteTask(task)">Delete</button>
      </div>
    </main>
    <footer>
      <button @click="page--" :disabled="page <= 1">Previous</button>
      <span>Page {{ page }}</span>
      <button @click="page++">Next</button>
    </footer>
  </div>
</template>
