// projects/create-remult/templates/nuxt/demo/Tile.vue
<template>
  <div :class="['tile', status?.toLowerCase(), width, className]">
    <div class="tile__header">
      <h3 class="tile__title">{{ title }}</h3>
      <div class="tile__subtitle">{{ subtitle }}</div>
      <img
        v-if="icon"
        :src="icon + '.svg'"
        :alt="`${icon} icon`"
        class="tile__icon"
      />
      <div v-else-if="status" class="tile__status-indicator"></div>
    </div>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { defineProps } from "vue";

type TileStatus = "Success" | "Error" | "Warning" | "Info" | "Loading";

interface TileProps {
  title: string;
  subtitle: string;
  status?: TileStatus;
  width?: "full" | "half" | "third" | "fourth";
  icon?: string;
  className?: string;
}

defineProps<TileProps>();
</script>

// projects/create-remult/templates/sveltekit/src/demo/Tile.svelte
<script lang="ts" context="module">
  export type TileStatus = "Success" | "Error" | "Warning" | "Info" | "Loading";
  export type WidthOption = "full" | "half" | "third" | "fourth";
</script>

<script lang="ts">
  export let title: string;
  export let subtitle: string | undefined;
  export let icon = "";
  export let className = "";

  // Define the allowed values for status and width if using TypeScript

  export let status: TileStatus = "Loading";
  export let width: WidthOption = "full";
</script>

<div class={`tile ${status?.toLowerCase()} ${width} ${className}`}>
  <div class="tile__header">
    <h3 class="tile__title">{title}</h3>
    <div class="tile__subtitle">{subtitle}</div>
    {#if icon}
      <img src="{icon}.svg" alt="{icon} icon" class="tile__icon" />
    {:else if status}
      <div class="tile__status-indicator"></div>
    {/if}
  </div>
  <slot></slot>
</div>
