// projects/create-remult/templates/auth/sveltekit/src/demo/auth/CheckAuth.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { remult, type UserInfo } from "remult";

  let user: UserInfo | undefined | "loading" = "loading";

  onMount(async () => {
    user = await remult.initUser();
  });
</script>

{#if user === "loading"}
  <div>Auth: ⌛</div>
{:else if remult.authenticated()}
  <div>
    Auth:✅ Hello {remult.user?.name}
    <a href="/auth/signout">Sign Out</a>
  </div>
{:else}
  <div>
    Auth:✅ Not authenticated, <a href="/auth/signin">Sign In</a>
  </div>
{/if}

// projects/create-remult/templates/auth/angular/src/app/demo/check-auth/check-auth.component.ts
import { Component, type OnInit } from '@angular/core';
import { remult } from 'remult';

@Component({
  selector: 'app-check-auth',
  standalone: true,
  imports: [],
  templateUrl: './check-auth.component.html',
})
export class CheckAuthComponent implements OnInit {
  loaded = false;

  remult = remult;
  async ngOnInit() {
    try {
      await remult.initUser();
      this.loaded = true;
    } catch {}
  }
}

@if (!loaded) { ⌛ } @else if (remult.authenticated()) {
<div>
  Auth:✅ Hello {{ remult.user?.name }} <a href="/auth/signout">Sign Out</a>
</div>

} @else {
<div>Auth:✅ Not authenticated, <a href="/auth/signin">Sign In</a></div>
}
