// projects/create-remult/templates/admin/vue/src/modules/ui/Admin.vue
<template>
  <Tile :title="'Admin'" :status="status" :subtitle="subtitle" width="half">
    <p>{{ message }}</p>
    <div class="button-row">
      <a v-if="canOpenAdmin" class="button" href="/api/admin">Open Admin</a>
    </div>
  </Tile>
</template>

<script setup lang="ts">
import { remult } from "remult";
import { ref, onMounted, computed } from "vue";
import Tile from "./Tile.vue";
type TileStatus = "Success" | "Error" | "Warning" | "Info" | "Loading";

const status = ref<TileStatus>("Loading");
const canOpenAdmin = ref(false);

const subtitle = computed(() =>
  status.value === "Error" ? "There seems to be an issue" : "",
);
const message = computed(() =>
  status.value === "Success"
    ? "Remult Admin is an autogenerated UI for managing your data."
    : "Is admin enabled in remultApi config?",
);

onMounted(() => {
  fetch(`${remult.apiClient.url}/admin/__entities-metadata`)
    .then((response) => {
      if (response.ok) {
        status.value = "Success";
        canOpenAdmin.value = true;
      } else {
        status.value = "Error";
        canOpenAdmin.value = false;
      }
    })
    .catch(() => {
      status.value = "Error";
      canOpenAdmin.value = false;
    });
});
</script>

// projects/create-remult/templates/admin/react/src/modules/ui/Admin.tsx
import { remult } from "remult";
import { useState, useEffect } from "react";
import Tile, { TileStatus } from "./Tile";

export default function Admin() {
  const [status, setStatus] = useState<TileStatus>("Loading");
  const [canOpenAdmin, setCanOpenAdmin] = useState(false);

  useEffect(() => {
    fetch(`${remult.apiClient.url}/admin/__entities-metadata`)
      .then((response) => {
        if (response.ok) {
          setStatus("Success");
          setCanOpenAdmin(true);
        } else {
          setStatus("Error");
          setCanOpenAdmin(false);
        }
      })
      .catch(() => {
        setStatus("Error");
        setCanOpenAdmin(false);
      });
  }, []);

  let subtitle = status === "Error" ? "There seems to be an issue" : "";
  let message =
    status === "Success"
      ? "Remult Admin is an autogenerated UI for managing your data."
      : "Is admin enabled in remultApi config?";

  return (
    <Tile title="Admin" status={status} subtitle={subtitle} width="half">
      <p>{message}</p>
      <div className="button-row">
        {canOpenAdmin && (
          <a className="button" href="/api/admin">
            Open Admin
          </a>
        )}
      </div>
    </Tile>
  );
}
