// projects/create-remult/templates/check-server/react/src/modules/server-status/ServerStatus.tsx
import { remult } from "remult";
import { Tile, type TileStatus } from "../ui";
import { useState, useEffect } from "react";

export default function ServerStatus() {
  const [status, setStatus] = useState<TileStatus>("Loading");
  const [error, setError] = useState<JSX.Element | string>();
  useEffect(() => {
    remult
      .initUser()
      .then(() => setStatus("Success"))
      .catch(async (e) => {
        setStatus("Error");

        if (e.message?.includes("the server configuration")) {
          setError(
            <>
              Make sure to set the <code>BETTER_AUTH_SECRET</code> in the{" "}
              <code>.env</code> file. <br />
              Read more at{" "}
              <a href="https://www.better-auth.com/docs/reference/options#secret">
                better-auth docs
              </a>
              .
            </>,
          );
        } else
          setError(
            <>
              Please run <code>npm run dev-node</code> in a separate terminal.
            </>,
          );
      });
  }, []);

  const subtitle =
    status === "Success"
      ? "Up and running"
      : status === "Error"
        ? "There seems to be an issue"
        : status;

  return (
    <Tile title="Server Status" status={status} subtitle={subtitle}>
      {status === "Error" ? (
        <>
          <p>{error!}</p>
        </>
      ) : status === "Loading" ? (
        <p>Looking for the server...</p>
      ) : (
        <>
          <p>
            Everything sparkling! API is ready to be consumed. Find more
            information in the{" "}
            <a target="_blank" href="https://remult.dev/docs/rest-api">
              docs
            </a>
            .
          </p>
        </>
      )}
    </Tile>
  );
}

// projects/create-remult/templates/check-server/angular/src/app/modules/server-status/server-status.component.ts
import { Component, OnInit } from "@angular/core";
import { remult } from "remult";
import { TileComponent, type TileStatus } from "../ui";

@Component({
  selector: "app-server-status",
  templateUrl: "./server-status.component.html",
  styles: [":host { display: contents; }"],
  standalone: true,
  imports: [TileComponent],
})
export class ServerStatusComponent implements OnInit {
  status: TileStatus = "Loading";
  error?: string;

  ngOnInit(): void {
    remult
      .initUser()
      .then(() => {
        this.status = "Success";
      })
      .catch((e) => {
        this.status = "Error";

        if (e.message?.includes("the server configuration")) {
          this.error =
            "Make sure to set the BETTER_AUTH_SECRET in the .env file.\nRead more at https://www.better-auth.com/docs/reference/options#secret.";
        } else {
          this.error = "Please run npm run dev-node in a separate terminal.";
        }
      });
  }

  get subtitle(): string {
    if (this.status === "Success") {
      return "Up and running";
    } else if (this.status === "Error") {
      return "There seems to be an issue";
    } else {
      return this.status;
    }
  }
}

<app-tile title="Server Status" [status]="status" [subtitle]="subtitle">
  @if (status === 'Error') {
  <p>{{ error }}</p>
  } @else if (status === 'Loading') {
  <p>Looking for the server...</p>
  } @else {
  <p>
    Everything sparkling! API is ready to be consumed. Find more information in
    the
    <a target="_blank" href="https://remult.dev/docs/rest-api">docs</a>.
  </p>
  }
</app-tile>
