// projects/create-remult/templates/admin/react/src/demo/Admin.tsx
import { useState, useEffect } from "react";
import Tile, { TileStatus } from "./Tile";

export default function Admin() {
  const [status, setStatus] = useState<TileStatus>("Loading");
  const [canOpenAdmin, setCanOpenAdmin] = useState(false);

  useEffect(() => {
    fetch("/api/admin") // Assuming there's a ping endpoint to check server status
      .then((response) => {
        if (response.ok) {
          setStatus("Success");
          setCanOpenAdmin(true);
        } else {
          setStatus("Error");
          setCanOpenAdmin(false);
        }
      })
      .catch(() => {
        setStatus("Error");
        setCanOpenAdmin(false);
      });
  }, []);

  let subtitle = status === "Error" ? "There seems to be an issue" : "";
  let message =
    status === "Success"
      ? "Remult Admin is an autogenerated UI for managing your data."
      : "Failed to connect to Remult server.";

  return (
    <Tile title="Admin" status={status} subtitle={subtitle} width="half">
      <p>{message}</p>
      <div className="button-row">
        {canOpenAdmin && (
          <a className="button" href="/api/admin">
            Open Admin
          </a>
        )}
      </div>
    </Tile>
  );
}

// projects/create-remult/templates/admin/sveltekit/src/demo/admin.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Tile, { type TileStatus } from "./Tile.svelte";

  let status: TileStatus = "Loading";
  let canOpenAdmin = false;

  onMount(() => {
    fetch("/api/admin")
      .then((response) => {
        if (response.ok) {
          status = "Success";
          canOpenAdmin = true;
        } else {
          status = "Error";
          canOpenAdmin = false;
        }
      })
      .catch(() => {
        status = "Error";
        canOpenAdmin = false;
      });
  });

  $: subtitle = status === "Error" ? "There seems to be an issue" : "";
  $: message =
    status === "Success"
      ? "Remult Admin is an autogenerated UI for managing your data."
      : "Failed to connect to Remult server.";
</script>

<Tile title="Admin" {status} {subtitle} width="half">
  <p>{message}</p>
  <div class="button-row">
    {#if canOpenAdmin}
      <a class="button" href="/api/admin"> Open Admin </a>
    {/if}
  </div>
</Tile>
