// projects/remult-admin/src/components/RelationField.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import type { FieldUIInfo } from '../../../core/server/remult-admin'
  import SelectDialog from './SelectDialog.svelte'
  import { godStore } from '../stores/GodStore.js'

  export let value: any
  export let info: FieldUIInfo

  let displayValue = ''
  let dialogOpen = false

  const dispatch = createEventDispatcher()

  function dispatchChange(_data) {
    dispatch('change', { _data })
  }

  onMount(async () => {
    const val = await $godStore.displayValueFor(info, value)
    displayValue = val
  })

  $: {
    ;(async () => {
      const val = await $godStore.displayValueFor(info, value)
      displayValue = val
    })()
  }
</script>

<div>
  {displayValue}
  <button class="icon-button" on:click={() => (dialogOpen = true)}>🔎</button>
  {#if dialogOpen}
    <SelectDialog
      relation={info.relationToOne}
      on:close={() => (dialogOpen = false)}
      on:select={(e) => {
        value = e.detail._data
        dispatchChange(value)
      }}
    />
  {/if}
</div>

// projects/remult-admin/src/test-project/components/RelationField.tsx
import { useEffect, useState } from 'react'
import { FieldUIInfo } from '../../lib/entity-info'
import { God } from '../God'
import { SelectDialog } from './SelectDialog'

export function RelationField({
  value,
  onChange,
  info,
  god,
}: {
  value: any
  onChange: (value: any) => void
  info: FieldUIInfo
  god: God
}) {
  const [displayValue, setDisplayValue] = useState('')
  const [dialogOpen, setDialogOpen] = useState(false)
  useEffect(() => {
    god.displayValueFor(info, value).then((value) => {
      setDisplayValue(value)
    })
  }, [value])
  return (
    <div>
      <button onClick={() => setDialogOpen(true)}>🔎</button>
      {displayValue}
      {dialogOpen && (
        <SelectDialog
          relation={info.relationToOne!}
          onSelect={onChange}
          god={god}
          onClose={() => setDialogOpen(false)}
        />
      )}
    </div>
  )
}
