// examples/nuxt-todo/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { remult, type UserInfo } from 'remult'
import { Task } from './shared/task'
import { TasksController } from './shared/tasksController'

const { status, data, signIn, signOut, refresh } = await useAuth({
  required: false,
})
const taskRepo = remult.repo(Task)
const tasks = ref<Task[]>([])
onMounted(() => {
  remult.user = data.value?.user as UserInfo
  if (status.value === 'unauthenticated') signIn()
  else if (status.value === 'authenticated')
    return onUnmounted(
      taskRepo
        .liveQuery({
          limit: 20,
          orderBy: { createdAt: 'asc' },
          // where: { completed: true },
        })
        .subscribe((info) => (tasks.value = info.applyChanges(tasks.value))),
    )
})
const newTaskTitle = ref('')
async function addTask() {
  try {
    const newTask = await taskRepo.insert({ title: newTaskTitle.value })
    newTaskTitle.value = ''
  } catch (error) {
    alert((error as { message: string }).message)
  }
}
async function saveTask(task: Task) {
  try {
    await taskRepo.save(task)
  } catch (error) {
    alert((error as { message: string }).message)
  }
}
async function deleteTask(task: Task) {
  try {
    await taskRepo.delete(task)
  } catch (error) {
    alert((error as { message: string }).message)
  }
}
async function setAllCompleted(completed: boolean) {
  TasksController.setAllCompleted(completed)
}
</script>
<template>
  <ClientOnly>
    <div v-if="status === 'authenticated'">
      <h1>todos</h1>
      <main>
        <div>
          Hello {{ remult.user.name }}
          <button @click="signOut()">Sign Out</button>
        </div>

        <form
          @submit.prevent="addTask()"
          v-if="taskRepo.metadata.apiInsertAllowed()"
        >
          <input v-model="newTaskTitle" placeholder="What needs to be done?" />
          <button>Add</button>
        </form>
        <div v-for="task in tasks" v-bind:key="task.id">
          <input
            type="checkbox"
            v-model="task.completed"
            @change="saveTask(task)"
          />
          <input v-model="task.title" />
          <button @click="saveTask(task)">Save</button>
          <button
            v-if="taskRepo.metadata.apiDeleteAllowed(task)"
            @click="deleteTask(task)"
          >
            Delete
          </button>
        </div>
        <div>
          <button @click="setAllCompleted(true)">Set All as Completed</button>
          <button @click="setAllCompleted(false)">
            Set All as Uncompleted
          </button>
        </div>
      </main>
    </div>
  </ClientOnly>
</template>

// examples/nextjs-app-router-todo/src/app/page.tsx
"use client"
import { FormEvent, useEffect, useState } from "react"
import { UserInfo, remult } from "remult"
import { Task } from "../shared/task"
import { TasksController } from "../shared/tasksController"
import { signIn, signOut, useSession } from "next-auth/react"

const taskRepo = remult.repo(Task)

export default function Page() {
  const [tasks, setTasks] = useState<Task[]>([])
  const [newTaskTitle, setNewTaskTitle] = useState("")

  const session = useSession()

  useEffect(() => {
    remult.user = session.data?.user as UserInfo
    if (session.status === "unauthenticated") signIn()
    else if (session.status === "authenticated")
      return taskRepo
        .liveQuery({
          where: {
            completed: undefined
          }
        })
        .subscribe((info) => setTasks(info.applyChanges))
  }, [session])
  if (session.status !== "authenticated") return <></>
  async function addTask(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    try {
      const newTask = await taskRepo.insert({ title: newTaskTitle })
      setNewTaskTitle("")
    } catch (error: any) {
      alert(error.message)
    }
  }

  async function setAllCompleted(completed: boolean) {
    await TasksController.setAllCompleted(completed)
  }

  return (
    <div>
      <h1>Todos</h1>
      <main>
        <div>
          Hello {remult.user?.name}
          <button onClick={() => signOut()}>Sign Out</button>
        </div>
        {taskRepo.metadata.apiInsertAllowed() && (
          <form onSubmit={(e) => addTask(e)}>
            <input
              value={newTaskTitle}
              placeholder="What needs to be done?"
              onChange={(e) => setNewTaskTitle(e.target.value)}
            />
            <button>Add</button>
          </form>
        )}
        {tasks.map((task) => {
          async function deleteTask() {
            try {
              await taskRepo.delete(task)
              setTasks((tasks) => tasks.filter((t) => t !== task))
            } catch (error: any) {
              alert(error.message)
            }
          }
          function setTask(value: Task) {
            setTasks((tasks) => tasks.map((t) => (t === task ? value : t)))
          }
          async function setCompleted(completed: boolean) {
            setTask(await taskRepo.save({ ...task, completed }))
          }
          function setTitle(title: string) {
            setTask({ ...task, title })
          }

          async function doSaveTask() {
            try {
              setTask(await taskRepo.save(task))
            } catch (error: any) {
              alert(error.message)
            }
          }

          return (
            <div key={task.id}>
              <input
                type="checkbox"
                checked={task.completed}
                onChange={(e) => setCompleted(e.target.checked)}
              />
              <input
                value={task.title}
                onChange={(e) => setTitle(e.target.value)}
              />
              <button onClick={() => doSaveTask()}>Save</button>
              {taskRepo.metadata.apiDeleteAllowed() && (
                <button onClick={() => deleteTask()}>Delete</button>
              )}
            </div>
          )
        })}
        <div>
          <button onClick={(e) => setAllCompleted(true)}>
            Set all completed
          </button>
          <button onClick={(e) => setAllCompleted(false)}>
            Set all uncompleted
          </button>
        </div>
      </main>
    </div>
  )
}
