// examples/bun-react-hono-monorepo-todo/packages/frontend/src/App.tsx
import { FormEvent, useEffect, useState } from "react";
import { Task, TasksController, remult } from "shared";

export default function App() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [newTaskTitle, setNewTaskTitle] = useState("");

  const taskRepo = remult.repo(Task);

  const addTask = async (e: FormEvent) => {
    e.preventDefault();
    try {
      await TasksController.insertTask({ title: newTaskTitle });
      setNewTaskTitle("");
    } catch (error) {
      alert((error as { message: string }).message);
    }
  };

  const setAllCompleted = async (completed: boolean) => {
    await TasksController.setAllCompleted(completed);
  };

  useEffect(() => {
    return taskRepo
      .liveQuery({
        limit: 20,
        orderBy: { createdAt: "asc" },
      })
      .subscribe((info) => setTasks(info.applyChanges));
  }, []);
  return (
    <div>
      <h1>Todos</h1>
      <main>
        <div>
          <button onClick={() => setAllCompleted(true)}>
            Set All Completed
          </button>
          <button onClick={() => setAllCompleted(false)}>
            Set All Uncompleted
          </button>
        </div>
        {taskRepo.metadata.apiInsertAllowed() && (
          <form onSubmit={addTask}>
            <input
              value={newTaskTitle}
              placeholder="What needs to be done?"
              onChange={(e) => setNewTaskTitle(e.target.value)}
            />
            <button>Add</button>
          </form>
        )}
        {tasks.map((task) => {
          const setTask = (value: Task) =>
            setTasks((tasks) => tasks.map((t) => (t === task ? value : t)));

          const setCompleted = async (completed: boolean) =>
            await TasksController.saveTask({ ...task, completed });

          const setTitle = (title: string) => setTask({ ...task, title });

          const saveTask = async () => {
            try {
              await TasksController.saveTask(task);
            } catch (error) {
              alert((error as { message: string }).message);
            }
          };

          const deleteTask = async () => {
            try {
              await TasksController.deleteTask(task);
            } catch (error) {
              alert((error as { message: string }).message);
            }
          };

          return (
            <div key={task.id}>
              <input
                type="checkbox"
                checked={task.completed}
                onChange={(e) => setCompleted(e.target.checked)}
              />
              <input
                value={task.title}
                onChange={(e) => setTitle(e.target.value)}
              />
              <button onClick={saveTask}>Save</button>
              {taskRepo.metadata.apiDeleteAllowed(task) && (
                <button onClick={deleteTask}>Delete</button>
              )}
            </div>
          );
        })}
      </main>
    </div>
  );
}

// examples/vue-todo/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue"
import { remult } from "remult"
import { Task } from "./shared/Task"
import { TasksController } from "./shared/TasksController"

const taskRepo = remult.repo(Task)
const tasks = ref<Task[]>([])
onMounted(() =>
  onUnmounted(
    taskRepo
      .liveQuery({
        limit: 20,
        orderBy: { createdAt: "asc" },
        // where: { completed: true },
      })
      .subscribe((info) => (tasks.value = info.applyChanges(tasks.value)))
  )
)
const newTaskTitle = ref("")
async function addTask() {
  try {
    const newTask = await taskRepo.insert({ title: newTaskTitle.value })
    //tasks.value.push(newTask)
    newTaskTitle.value = ""
  } catch (error) {
    alert((error as { message: string }).message)
  }
}
async function saveTask(task: Task) {
  try {
    await taskRepo.save(task)
  } catch (error) {
    alert((error as { message: string }).message)
  }
}
async function deleteTask(task: Task) {
  try {
    //await taskRepo.delete(task)
    tasks.value = tasks.value.filter((t) => task !== t)
  } catch (error) {
    alert((error as { message: string }).message)
  }
}
async function setAllCompleted(completed: boolean) {
  TasksController.setAllCompleted(completed)
}
</script>
<template>
  <div>
    <h1>todos</h1>
    <main>
      <form
        @submit.prevent="addTask()"
        v-if="taskRepo.metadata.apiInsertAllowed()"
      >
        <input v-model="newTaskTitle" placeholder="What needs to be done?" />
        <button>Add</button>
      </form>
      <div v-for="task in tasks">
        <input
          type="checkbox"
          v-model="task.completed"
          @change="saveTask(task)"
        />
        <input v-model="task.title" />
        <button @click="saveTask(task)">Save</button>
        <button
          v-if="taskRepo.metadata.apiDeleteAllowed(task)"
          @click="deleteTask(task)"
        >
          Delete
        </button>
      </div>
      <div>
        <button @click="setAllCompleted(true)">Set All as Completed</button>
        <button @click="setAllCompleted(false)">Set All as Uncompleted</button>
      </div>
    </main>
  </div>
</template>
./shared/Task
