// examples/angular-todo/src/app/auth/auth.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { UserInfo, remult } from 'remult';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { TodoComponent } from '../todo/todo.component';

@Component({
  selector: 'app-auth',
  standalone: true,
  imports: [CommonModule, FormsModule, TodoComponent, HttpClientModule],
  templateUrl: './auth.component.html',
  styleUrl: './auth.component.css',
})
export class AuthComponent implements OnInit {
  constructor(private http: HttpClient) {}

  signInUsername = '';
  remult = remult;

  signIn() {
    this.http
      .post<UserInfo>('/api/signIn', {
        username: this.signInUsername,
      })
      .subscribe({
        next: (user) => {
          this.remult.user = user;
          this.signInUsername = '';
        },
        error: (error) => alert(error.error),
      });
  }

  signOut() {
    this.http
      .post('/api/signOut', {})
      .subscribe(() => (this.remult.user = undefined));
  }

  ngOnInit() {
    this.http
      .get<UserInfo>('/api/currentUser')
      .subscribe((user) => (this.remult.user = user));
  }
}

<ng-container *ngIf="!remult.authenticated()">
  <h1>todos</h1>
  <main>
    <form (submit)="signIn()">
      <input
        [(ngModel)]="signInUsername"
        placeholder="Username, try Steve or Jane"
        name="username"
      />
      <button>Sign in</button>
    </form>
  </main>
</ng-container>
<ng-container *ngIf="remult.authenticated()">
  <header>
    Hello {{ remult.user?.name }}
    <button (click)="signOut()">Sign Out</button>
  </header>
  <app-todo></app-todo>
</ng-container>

// examples/vue-todo/src/Auth.vue
<script setup lang="ts">
import { onMounted, ref } from "vue"
import { remult } from "remult"
import App from "./App.vue"

const username = ref("")
const signedIn = ref(false)

const signIn = async () => {
  const result = await fetch("/api/signIn", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ username: username.value }),
  })
  if (result.ok) {
    remult.user = await result.json()
    signedIn.value = true
    username.value = ""
  } else alert(await result.json())
}
const signOut = async () => {
  await fetch("/api/signOut", {
    method: "POST",
  })
  remult.user = undefined
  signedIn.value = false
}

onMounted(async () => {
  remult.user = await fetch("/api/currentUser").then((r) => r.json())
  signedIn.value = remult.authenticated()
})
</script>
<template>
  <div v-if="!signedIn">
    <h1>todos</h1>
    <main>
      <form @submit.prevent="signIn()">
        <input v-model="username" placeholder="Username, try Steve or Jane" />
        <button>Sign in</button>
      </form>
    </main>
  </div>
  <div v-else>
    <header>
      Hello {{ remult.user!.name }}
      <button @click="signOut()">Sign Out</button>
    </header>
    <App />
  </div>
</template>
