// projects/create-remult/templates/crud/angular/src/app/modules/todo/todo.component.ts
import { Component, type OnInit } from "@angular/core";
import { FormsModule } from "@angular/forms";

import { Task } from "../../../demo/todo/Task.js";
import { repo } from "remult";
import { TileComponent } from "../tile/tile.component";
import { CommonModule } from "@angular/common";

@Component({
  selector: "app-todo",
  standalone: true,
  imports: [FormsModule, TileComponent, CommonModule],
  styles: [":host { display: contents; }"],
  templateUrl: "./todo.component.html",
})
export class TodoComponent implements OnInit {
  tasks: Task[] = [];
  hideCompleted = false;
  ngOnInit() {
    this.loadTasks();
  }
  toggleHideCompleted() {
    this.hideCompleted = !this.hideCompleted;
    this.loadTasks();
  }
  async loadTasks() {
    this.tasks = await repo(Task).find({
      where: {
        completed: this.hideCompleted ? false : undefined,
      },
      orderBy: {
        createdAt: "asc",
      },
    });
  }

  newTaskTitle = "";
  async addTask() {
    try {
      const newTask = await repo(Task).insert({ title: this.newTaskTitle });
      this.tasks.push(newTask);
      this.newTaskTitle = "";
    } catch (error: any) {
      alert(error.message);
    }
  }
  async saveTask(task: Task) {
    try {
      await repo(Task).save(task);
    } catch (error: any) {
      alert(error.message);
    }
  }
  async deleteTask(task: Task) {
    await repo(Task).delete(task);
    this.tasks = this.tasks.filter((t) => t !== task);
  }
}

<app-tile
  title="Todos"
  subtitle="Fully functional todo app"
  icon=""
  width="full"
  class="todo"
>
  <main>
    <form (ngSubmit)="addTask()">
      <input
        type="text"
        [(ngModel)]="newTaskTitle"
        name="newTaskTitle"
        placeholder="What needs to be done?"
      />
      <button type="submit">
        <img src="/plus.svg" alt="Add" />
      </button>
    </form>

    @if (tasks.length > 0) { @for ( task of tasks; track task.id) {
    <div
      class="todo__task"
      [ngClass]="{ completed: task.completed }"
      (click)="task.completed = !task.completed; saveTask(task)"
    >
      <input
        type="checkbox"
        [checked]="task.completed"
        (click)="$event.stopPropagation()"
        (change)="saveTask(task)"
      />
      <span>{{ task.title }}</span>
      <button (click)="deleteTask(task); $event.stopPropagation()">
        <img src="trash.svg" alt="Delete" />
      </button>
    </div>
    } } @else {
    <p class="todo__empty">
      There is nothing to do right now, try adding some todos.
    </p>
    }

    <div class="button-row">
      <button (click)="toggleHideCompleted()">
        {{ hideCompleted ? "Show" : "Hide" }} completed
      </button>
    </div>
  </main>
</app-tile>

// projects/create-remult/templates/crud/react/src/modules/todo/Todo.tsx
import { useEffect, useState, type FormEvent } from "react";
import { Tile } from "../ui";
import { repo } from "remult";
import { Task } from "./Task";

export default function Todo() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [hideCompleted, setHideCompleted] = useState(false);

  useEffect(() => {
    repo(Task)
      .find({
        where: hideCompleted ? { completed: false } : undefined,
        orderBy: {
          createdAt: "desc",
        },
      })
      .then(setTasks);
  }, [hideCompleted]);
  function toggleHideCompleted() {
    setHideCompleted(!hideCompleted);
  }

  const [newTaskTitle, setNewTaskTitle] = useState("");

  async function addTask(e: FormEvent) {
    e.preventDefault();
    try {
      const newTask = await repo(Task).insert({ title: newTaskTitle });
      setTasks([newTask, ...tasks]);
      setNewTaskTitle("");
    } catch (error: any) {
      alert((error as { message: string }).message);
    }
  }
  async function setCompleted(task: Task, completed: boolean) {
    await repo(Task).update(task.id, { completed });
    task.completed = completed;
    setTasks([...tasks]);
  }
  async function deleteTask(task: Task) {
    await repo(Task).delete(task.id);
    setTasks(tasks.filter((x) => x !== task));
  }

  return (
    <Tile
      title="Todos"
      subtitle="Fully functional todo app"
      icon=""
      width="full"
      className="todo"
    >
      <main>
        <form onSubmit={addTask}>
          <input
            type="text"
            value={newTaskTitle}
            placeholder="What needs to be done?"
            onChange={(e) => setNewTaskTitle(e.target.value)}
          />
          <button>
            <img src="plus.svg" alt="Add" />
          </button>
        </form>
        {tasks.length > 0 ? (
          tasks.map((task) => (
            <div
              className={`todo__task ${task.completed ? "completed" : ""}`}
              key={task.id}
              onClick={() => setCompleted(task, !task.completed)}
            >
              <input
                type="checkbox"
                checked={task.completed}
                onChange={(e) => {
                  e.stopPropagation();
                  setCompleted(task, e.target.checked);
                }}
              />
              <span>{task.title}</span>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  deleteTask(task);
                }}
              >
                <img src="trash.svg" alt="Delete" />
              </button>
            </div>
          ))
        ) : (
          <p className="todo__empty">
            There is nothing to do right now, try adding some todos.
          </p>
        )}
        <div className="button-row">
          <button onClick={toggleHideCompleted}>
            {hideCompleted ? "Show" : "Hide"} completed
          </button>{" "}
        </div>
      </main>
    </Tile>
  );
}
