// projects/create-remult/templates/check-server/react/src/demo/CheckServer.tsx
import { useState, useEffect } from "react";

export default function CheckServer() {
  const [status, setStatus] = useState<"⌛" | "✅" | "❌">("⌛");
  useEffect(() => {
    fetch("/api/me")
      .then((x) => x.json())
      .then((x) => setStatus(x !== undefined ? "✅" : "❌"))
      .catch(() => setStatus("❌"));
  }, []);
  return (
    <div>
      Api status:{" "}
      {status === "❌" ? (
        <>
          {status} Please run <code>npm run dev-node</code> in a separate
          terminal
        </>
      ) : (
        status
      )}
    </div>
  );
}

// projects/create-remult/templates/check-server/angular/src/app/demo/check-server/check-server.component.ts
import { Component, signal, type OnInit } from '@angular/core';
import { remult } from 'remult';

@Component({
  selector: 'app-check-server',
  standalone: true,
  imports: [],
  providers: [],
  templateUrl: './check-server.component.html',
})
export class CheckServerComponent implements OnInit {
  status = signal<'⌛' | '✅' | '❌'>('⌛');

  constructor() {}

  async ngOnInit() {
    try {
      await remult.initUser();
      this.status.set('✅');
    } catch {
      this.status.set('❌');
    }
  }
}

<div>
  Api status: @if (status() === '❌') {
  {{ status() }} Please run <code>npm run dev-node</code> in a separate terminal
  } @else {
  {{ status() }}
  }
</div>
