// projects/create-remult/templates/check-server/vue/src/demo/CheckServer.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

const status = ref<"⌛" | "✅" | "❌">("⌛");

onMounted(() => {
  fetch("/api/me")
    .then((x) => x.json())
    .then((x) => (status.value = x !== undefined ? "✅" : "❌"))
    .catch(() => (status.value = "❌"));
});
</script>

<template>
  <div>
    Api status:
    <template v-if="status === '❌'">
      {{ status }} Please run <code>npm run dev-node</code> in a separate
      terminal
    </template>
    <template v-else>
      {{ status }}
    </template>
  </div>
</template>

// projects/create-remult/templates/check-server/react/src/demo/CheckServer.tsx
import { useState, useEffect } from "react";

export default function CheckServer() {
  const [status, setStatus] = useState<"⌛" | "✅" | "❌">("⌛");
  useEffect(() => {
    fetch("/api/me")
      .then((x) => x.json())
      .then((x) => setStatus(x !== undefined ? "✅" : "❌"))
      .catch(() => setStatus("❌"));
  }, []);
  return (
    <div>
      Api status:{" "}
      {status === "❌" ? (
        <>
          {status} Please run <code>npm run dev-node</code> in a separate
          terminal
        </>
      ) : (
        status
      )}
    </div>
  );
}
