// projects/remult-admin/src/lib/ui/EditableField.svelte
<script lang="ts">
  import type { FieldUIInfo } from '../../../../core/server/remult-admin'
  import RelationField from './RelationField.svelte'
  import { type Content, JSONEditor } from 'svelte-jsoneditor'

  export let value: any
  export let info: FieldUIInfo

  let dialogJSON: HTMLDialogElement | null = null

  const onChange = (content: Content) => {
    // @ts-ignore
    if (JSON.stringify(content.json) != JSON.stringify(value)) {
      // @ts-ignore
      value = content.json
    }
  }
</script>

<!-- TODO Ermin? When readonly? -->
<!-- {info.dbReadOnly} -->
{#if info.relationToOne}
  <RelationField bind:value {info} on:change />
{:else if info.type == 'json'}
  <button
    class="icon-button"
    on:click={() => {
      // showJSON = true
      dialogJSON.showModal()
      // ref.current?.showModal()
    }}
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width={1.5}
      stroke="currentColor"
      class="w-6 h-6"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M17.25 6.75 22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3-4.5 16.5"
      />
    </svg>
  </button>
  <dialog bind:this={dialogJSON} on:close={() => {}} class="dialog-big">
    <button on:click={() => dialogJSON.close()}>Close</button>
    <div class="dialog-content">
      <JSONEditor content={{ json: value ?? {} }} {onChange} />
    </div>
  </dialog>
{:else if info.type == 'boolean'}
  <select bind:value>
    <option value={false}>False</option>
    <option value={true}>True</option>
  </select>
{:else if info.values && info.values.length > 0}
  <select bind:value>
    {#each info.values as option}
      {#if typeof option == 'object'}
        <option value={String(option.id)}>{option.caption}</option>
      {:else}
        <option value={String(option)}>{option}</option>
      {/if}
    {/each}
  </select>
{:else if info.type == 'number'}
  <input bind:value on:change type="number" />
{:else}
  <input bind:value on:change />
{/if}

<style>
  .dialog-big {
    width: 90vw;
    height: 90vh;
  }

  .dialog-content {
    display: flex;
    flex-direction: 'column';
    height: '100%';
  }
</style>

// projects/remult-admin/src/components/EditableField.tsx
import { FieldUIInfo } from '../../../core/server/remult-admin'
import { God } from '../God'
import { RelationField } from './RelationField'
import {
  Content,
  JSONContent,
  JSONEditor,
  JSONEditorPropsOptional,
} from 'vanilla-jsoneditor'
import { useEffect, useMemo, useRef, useState } from 'react'

export function EditableField({
  value,
  onChange,
  info,
  god,
}: {
  value: any
  onChange: (value: any) => void
  info: FieldUIInfo
  god: God
}) {
  if (info.relationToOne)
    return (
      <RelationField value={value} onChange={onChange} info={info} god={god} />
    )
  if (info.type == 'json')
    return <EditableJson {...{ value, onChange, info, god }} />
  return <input value={value} onChange={(e) => onChange(e.target.value)} />
}

export function EditableJson({
  value,
  onChange,
  info,
  god,
}: {
  value: any
  onChange: (value: any) => void
  info: FieldUIInfo
  god: God
}) {
  const ref = useRef<HTMLDialogElement>(null)

  const [show, setShow] = useState(false)
  return (
    <>
      <button
        className="icon-button"
        onClick={() => {
          setShow(true)

          ref.current?.showModal()
        }}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-6 h-6"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M17.25 6.75 22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3-4.5 16.5"
          />
        </svg>
      </button>
      <dialog
        ref={ref}
        onClose={() => setShow(false)}
        style={{
          width: '90vw',
          height: '90vh',
        }}
      >
        <div
          style={{ flexDirection: 'column', display: 'flex', height: '100%' }}
        >
          {show && (
            <SvelteJSONEditor
              content={{ json: value }}
              onChange={(x: any) => {
                console.log(x)
                if (JSON.stringify(x.json) != JSON.stringify(value)) {
                  onChange(x.json)
                }
              }}
            />
          )}
          <button onClick={() => ref.current?.close()}>Close</button>
        </div>
      </dialog>
    </>
  )
}

export default function SvelteJSONEditor(props: JSONEditorPropsOptional) {
  const refContainer = useRef<HTMLDivElement>(null)
  const refEditor = useRef<JSONEditor | null>()

  useEffect(() => {
    // create editor
    if (refContainer.current) {
      refEditor.current = new JSONEditor({
        target: refContainer.current,
        props: {},
      })

      return () => {
        // destroy editor
        if (refEditor.current) {
          refEditor.current.destroy()
          refEditor.current = null
        }
      }
    }
  }, [refEditor.current])

  // update props
  useEffect(() => {
    if (refEditor.current) {
      refEditor.current.updateProps(props)
    }
  }, [props])

  return <div ref={refContainer} style={{ flexGrow: 1 }}></div>
}
