// projects/create-remult/templates/auth/sveltekit/src/demo/auth/CheckAuth.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { remult, type UserInfo } from "remult";

  let user: UserInfo | undefined | "loading" = "loading";

  onMount(async () => {
    user = await remult.initUser();
  });
</script>

{#if user === "loading"}
  <div>Auth: ⌛</div>
{:else if remult.authenticated()}
  <div>
    Auth:✅ Hello {remult.user?.name}
    <a href="/auth/signout">Sign Out</a>
  </div>
{:else}
  <div>
    Auth:✅ Not authenticated, <a href="/auth/signin">Sign In</a>
  </div>
{/if}

// projects/create-remult/templates/auth/react/src/demo/auth/CheckAuth.tsx
import { useState, useEffect } from "react";
import { type UserInfo, remult } from "remult";

export default function Auth() {
  const [user, setUser] = useState<UserInfo | undefined | "loading">("loading");
  useEffect(() => {
    remult.initUser().then(setUser);
  }, []);
  if (user === "loading") return <div>Auth: ⌛</div>;
  if (remult.authenticated())
    return (
      <div>
        Auth:✅ Hello {remult.user?.name} <a href="/auth/signout">Sign Out</a>
      </div>
    );
  return (
    <div>
      Auth:✅ Not authenticated, <a href="/auth/signin">Sign In</a>
    </div>
  );
}
