// projects/create-remult/templates/auth/sveltekit/src/demo/auth/Auth.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { remult } from "remult";
  import Tile from "../Tile.svelte";
  import type { TileStatus } from "../Tile.svelte";

  let status: TileStatus = "Loading";
  let errorType: "missingSecret" | "other" | null = null;
  let tileSubtitle = "";

  onMount(() => {
    remult
      .initUser()
      .then(() => {
        status = "Success";
      })
      .catch((e) => {
        status = "Error";
        if (e.message.includes("the server configuration")) {
          errorType = "missingSecret";
        } else {
          errorType = "other";
        }
      });
  });

  $: {
    if (status === "Loading") {
      tileSubtitle = "Checking your authentication status";
    } else if (status === "Error") {
      tileSubtitle = "There seems to be an issue";
    }
  }
</script>

<Tile
  title="Auth"
  {status}
  subtitle={tileSubtitle}
  className="auth"
  width="half"
>
  {#if status === "Loading"}
    <!-- You can add a loading indicator here if needed -->
  {:else if status === "Error"}
    {#if errorType === "missingSecret"}
      <p>
        Make sure to set the <code>AUTH_SECRET</code> in the <code>.env</code>
        file. <br />
        Read more at
        <a href="https://errors.authjs.dev#missingsecret">auth.js docs</a>.<br
        />
        Please check the server terminal console for more information.
      </p>
    {:else}
      <p>An error occurred. Please try again later.</p>
    {/if}
  {:else if remult.authenticated()}
    <p>
      You are authenticated as <strong>{remult.user?.name}</strong>
    </p>
    <div class="button-row">
      <a class="button" href="/auth/signout">Sign Out</a>
    </div>
  {:else}
    <p>You are currently not authenticated</p>
    <div class="button-row">
      <a class="button" href="/auth/signin">Sign In</a>
      <a class="button" target="_blank" href="https://authjs.dev"
        >Auth.js Docs</a
      >
    </div>
  {/if}
</Tile>

// projects/create-remult/templates/auth/angular/src/app/demo/auth/auth.component.ts
import { Component, OnInit } from "@angular/core";
import { remult } from "remult";
import { TileComponent, type TileStatus } from "../tile/tile.component";

@Component({
  selector: "app-auth",
  templateUrl: "./auth.component.html",
  styles: [":host { display: contents; }"],
  standalone: true,
  imports: [TileComponent],
})
export class AuthComponent implements OnInit {
  status: TileStatus = "Loading";
  error?: string;

  ngOnInit(): void {
    remult
      .initUser()
      .then(() => {
        this.status = "Success";
      })
      .catch((e) => {
        this.status = "Error";
        if (e.message.includes("the server configuration")) {
          this.error = `Make sure to set the AUTH_SECRET in the .env file.
Read more at https://errors.authjs.dev#missingsecret.
Please check the server terminal console for more information.`;
        }
      });
  }

  get tileSubtitle(): string {
    if (this.status === "Loading") {
      return "Checking your authentication status";
    } else if (this.status === "Error") {
      return "There seems to be an issue";
    } else {
      return "";
    }
  }

  get isAuthenticated(): boolean {
    return remult.authenticated();
  }

  get userName(): string | undefined {
    return remult.user?.name;
  }
}

<app-tile
  title="Auth"
  [status]="status"
  [subtitle]="tileSubtitle"
  class="auth"
  width="half"
>
  @if (status === 'Loading') {
  <!-- Optionally, add a loading indicator here -->
  } @else if (status === 'Error') {
  <p>{{ error }}</p>
  } @else if (isAuthenticated) {
  <p>
    You are authenticated as <strong>{{ userName }}</strong>
  </p>
  <div class="button-row">
    <a class="button" href="/auth/signout">Sign Out</a>
  </div>
  } @else {
  <p>You are currently not authenticated</p>
  <div class="button-row">
    <a class="button" href="/auth/signin">Sign In</a>
    <a class="button" target="_blank" href="https://authjs.dev">Auth.js Docs</a>
  </div>
  }
</app-tile>
